### ISSUE TITLE
complete argument doesn't compose, should be removed

### ISSUE THREAD

**Issue by trxcllnt** [staltz/fantasy-observable#2]
Observables are push-duals of Enumerables (lists). The notion of a "return" value isn't a thing enumerating a list of values. Even in JS, where the concept was added to support coroutines, it's rarely used, and widely seen as a mistake and source of pain. Return values don't compose through all possible operations, which will confuse and demoralize people. Let's correct this mistake early on.

**Comment by staltz** [comment]
I agree with you, the only reason it's there is because most.js uses this argument: https://github.com/cujojs/most/blob/master/docs/api.md#streamsubscribeobserver---subscription and I want to provide maximum interoperability between libraries. Note: it's an optional argument.

I'll ask @briancavalier to weigh in on this issue.

**Comment by briancavalier** [comment]
I'm ok w/removing it here and deprecating it in most.

**Comment by staltz** [comment]
Good, so it's resolved. https://github.com/staltz/fantasy-observable/commit/d7c8ca65b5a77949d5a809b5f749b17f7955cca3
