### ISSUE TITLE
Relationship to es-observable proposal

### ISSUE THREAD

**Issue by RangerMauve** [staltz/fantasy-observable#7]
Hello,
I was wondering if you could clarify how this project relates to the es-observable spec. Is the goal of this to eventually merge with the spec, or is this going to be standalone with the goal of ignoring the es-observable spec and having it be withdrawn?

**Comment by mightyiam** [comment]
@staltz thinks this is better than current ES proposal. Intends to use this pattern in his works. Most notably Cycle.js.
That's what I've gathered, at least. May not be accurate or complete.

**Comment by staltz** [comment]
@RangerMauve this was born out of disagreement with the ES Observable deviating significantly due to convergence with CancelTokens. However, recently CancelTokens were dropped as a TC39 proposal. So now the ES Observable spec has opportunity to be redesigned.
We hope ES Observable spec ends up looking similar to Fantasy Observable, but right now it's hard to predict what will happen. Fantasy Observable is just a way of saying "we want good old Observables and nothing else". It's very conservative, and we hope ES Observable spec is also like this.

**Comment by appsforartists** [comment]
FWIW, I think the current TC39 proposal happens to conform to Fantasy Observable too.  The main difference seems to be that TC39 also specifies a `start` method in the observer and a `closed` getter in the subscription.  As all the existence of all current Observable libraries demonstrates, neither is crucial.

**Comment by chikamichi** [comment]
Note to readers: https://github.com/tc39/proposal-observable is the current es-observable proposal.
